// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PagefyCMS.Data;

#nullable disable

namespace PagefyCMS.Migrations
{
    [DbContext(typeof(PagefyDbContext))]
    [Migration("20250103120000_AddMetaDescriptionToPage")]
    partial class AddMetaDescriptionToPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");
#pragma warning restore 612, 618
        }
    }
}
